name: build

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm ci --no-audit
      - run: npm run lint
      - run: npm run test:cov
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
      - run: npm run build
        env:
          CI: true
